title: Nishant Vemulakonda # your name (or website title) here
logo: "/images/portfolioprofilepicture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Professional Summary</b>
  Blockchain & Data Science Professional with 7 years of IT experience.
  Strong Programming skills in Python, Solidity, JS.
  Deep understanding of various block chain platforms including Ethereum (smart contracts) Bitcoin & Stellar.
  In-depth knowledge of transaction validation / consensus algorithms like Proof of work, Stellar consensus protocol
  Hands-on experience with Smart Contrract development lifecycle.
  Passionate about building DAPPS on top of block chain.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/nishant-vemulakonda/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/itznishant/">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-UA-202901452-1 # your Google Analytics tracking ID here
