title: Nishant Vemulakonda # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Professional Summary
  Blockchain & Data Science Professional with 7 years of IT experience including BFSI and fin-tech domains.
  Strong Programming skills in Python, Solidity, JS.
  Deep understanding of various block chain platforms including Ethereum (smart contracts) Bitcoin & Stellar.
  In-depth knowledge of transaction validation / consensus algorithms like Proof of work, Stellar consensus protocol
  Passionate about new technologies, trends and their application in the cryptocurrency industry.
  Hands-on experience with Smart Contrract development tools like Truffle framework, Ganache, Web3 JS, Metamask
  Passionate about building DAPPS on top of block chain.
  Experience working collaboratively in a global team.
  Excellent written and spoken communication skills.
  <br><br>
  <br><br>
  Block Chain Developer - Ethereum, Smart contracts
  DeFi (Decentralised Finance) Bank
  Crypto Token Sale ICO DAPP
  Instant Crypto Exchange Dapp
  Election Voting DAPP

  <br><br>
  <a href="https://www.linkedin.com/in/nishant-vemulakonda/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/itznishant/">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-UA-202901452-1 # your Google Analytics tracking ID here
