title: Nishant Vemulakonda     # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Professional Summary</b>
  <br><br>
  ‣Blockchain & Data Science Professional 7 years of IT experience.
  ‣Strong Programming skills in Solidity, Python, JavaScript
  ‣Hands on experience with  building DAPPS with smart contracts on Ethereum EVM 
  ‣Excellent understanding of smart contract development lifecycle.
  <br><br>
  <a href="https://www.linkedin.com/in/nishant-vemulakonda/">View LinkedIn Profile</a> 
  <br><br>
  <a href="https://nishantv.medium.com">View Medium Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-UA-202901452-1 # your Google Analytics tracking ID here
